apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  #type: NodePort
  ports:
    - port: 3306
      #nodePort: 31000
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: initdb
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: abc_airlines
  MYSQL_DATABASE_URL: jdbc:mysql://mysql/abc_airlines
  initdb.sql: |
    use abc_airlines;
    CREATE TABLE abc_baggage (flightid int, baggages VARCHAR(40), passengerid int, passengername VARCHAR(40));
    CREATE TABLE seating (flightid int, passengerid int, passengername VARCHAR(40), seatno int);
    CREATE TABLE loyalty_points(passengerid int,flightid int, loyaltypoints int, passengername VARCHAR(40) );
    CREATE TABLE abc_teamd (flightid int, arrival VARCHAR(40), departure VARCHAR(40), flightdate VARCHAR(40),flighttime VARCHAR(40), passengerid int, passengername VARCHAR(40), passengerseat int,seatno int);
    CREATE TABLE reference_data(passengerid int, aircraft VARCHAR(40), arrival VARCHAR(40), city VARCHAR(40), country VARCHAR(40), currency VARCHAR(40), destination VARCHAR(40), passengername VARCHAR(40));
    CREATE TABLE check_in(flightid int, passengerid int);
    
    insert into abc_teamd values (1, "banglore", "hyd", "March", "six",101, "Pooja", 1, 10);
    insert into abc_teamd values (2, "hyd", "Pune", "March", "seven",102, "Spandana", 2, 11);
    insert into abc_baggage values (1, "89, 42, 94",12, "Farhan");
    insert into check_in values (1, 100);
    insert into check_in values (2, 200);
    insert into loyalty_points values (113,1, 15, "Alen");
    insert into loyalty_points values (101,2, 20, "Alex");
    insert into seating values (10, 101,"Pooja", 46);
    insert into reference_data values(2021001,'Indigo','Pune','Mumbai','India','rupee','Hyderabad','spandana');